# Generated by Django 6.0.5 on 2026-05-08 17:14

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField(help_text='Marquee message for users')),
                ('icon', models.CharField(default='fas fa-bell', help_text='FontAwesome icon class', max_length=50)),
                ('priority', models.CharField(choices=[('low', '🟢 Low'), ('medium', '🟡 Medium'), ('high', '🔴 High'), ('critical', '⚫ Critical')], default='medium', max_length=20)),
                ('color_bg', models.CharField(default='#28a745', help_text='Background color (hex)', max_length=20)),
                ('color_text', models.CharField(default='#ffffff', help_text='Text color (hex)', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_marquee', models.BooleanField(default=True, help_text='Show as scrolling marquee')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateTimeField(help_text='Notice visible from this date')),
                ('end_date', models.DateTimeField(help_text='Notice visible until this date')),
            ],
            options={
                'verbose_name_plural': 'Admin Notices',
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='category/')),
                ('description', models.TextField(blank=True)),
                ('position', models.CharField(choices=[('top', 'উপরে'), ('middle', 'মাঝখানে'), ('bottom', 'নিচে')], default='middle', help_text='ক্যাটেগরির অবস্থান (উপরে/মাঝখানে/নিচে)', max_length=10)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='প্রদর্শনের ক্রম')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('button_text', models.CharField(default='Order Now', max_length=100)),
                ('button_link', models.CharField(default='/register/', help_text='URL to navigate when button is clicked', max_length=300)),
                ('background_image', models.ImageField(upload_to='hero_slides/')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order of slides')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Hero Slides',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('postal_code', models.CharField(blank=True, max_length=10)),
                ('delivery_charge', models.DecimalField(decimal_places=2, default=Decimal('50.00'), max_digits=5)),
                ('latitude', models.FloatField(blank=True, help_text='Center latitude of service zone', null=True)),
                ('longitude', models.FloatField(blank=True, help_text='Center longitude of service zone', null=True)),
                ('radius', models.IntegerField(default=2000, help_text='Service radius in meters (e.g. 2000 = 2km)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Zones',
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_updates', models.BooleanField(default=True, help_text='Get notified on order status updates')),
                ('order_confirmation', models.BooleanField(default=True, help_text='Get notified when order is confirmed')),
                ('rider_assignments', models.BooleanField(default=True, help_text='Get notified when rider is assigned')),
                ('general_notifications', models.BooleanField(default=True, help_text='Get notified about general updates')),
                ('email_on_order_updates', models.BooleanField(default=True, help_text='Send email on order updates')),
                ('email_on_delivery', models.BooleanField(default=True, help_text='Send email when order is delivered')),
                ('email_on_cancellation', models.BooleanField(default=True, help_text='Send email if order is cancelled')),
                ('email_digests', models.BooleanField(default=False, help_text='Receive daily digest of all notifications')),
                ('enable_sound', models.BooleanField(default=True, help_text='Play sound for new notifications')),
                ('enable_browser_notifications', models.BooleanField(default=True, help_text='Show browser notifications')),
                ('quiet_hours_enabled', models.BooleanField(default=False, help_text='Enable quiet hours (no notifications)')),
                ('quiet_hours_start', models.TimeField(blank=True, help_text='Quiet hours start time (HH:MM)', null=True)),
                ('quiet_hours_end', models.TimeField(blank=True, help_text='Quiet hours end time (HH:MM)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preference', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Notification Preferences',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=20, unique=True)),
                ('customer_phone', models.CharField(max_length=15)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_address', models.TextField()),
                ('customer_city', models.CharField(max_length=100)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('address_formatted', models.TextField(blank=True, help_text='Google Maps থেকে formatted address', null=True)),
                ('status', models.CharField(choices=[('pending', 'অপেক্ষায়'), ('approved', 'অনুমোদিত'), ('confirmed', 'নিশ্চিত'), ('picked', 'রাইডার নিয়েছে'), ('delivered', 'ডেলিভার হয়েছে'), ('return_requested', 'রিটার্ন অনুরোধ'), ('cancelled', 'বাতিল')], default='pending', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('delivery_charge', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('payment_method', models.CharField(default='cash', max_length=20)),
                ('manager_approval_reason', models.TextField(blank=True, help_text='Rejection reason if declined', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manager_responded_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('manager', models.ForeignKey(blank=True, help_text='যে Manager এই অর্ডার approve করেছে', limit_choices_to={'profile__role': 'manager'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_orders', to=settings.AUTH_USER_MODEL)),
                ('rider', models.ForeignKey(blank=True, help_text='যে Rider deliver করবে', limit_choices_to={'profile__role': 'rider'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to=settings.AUTH_USER_MODEL)),
                ('zone', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.zone')),
            ],
            options={
                'verbose_name_plural': 'Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('order_confirmation', 'Order Confirmed'), ('order_processing', 'Order Processing'), ('order_picked', 'Order Picked'), ('order_in_transit', 'Order In Transit'), ('order_delivered', 'Order Delivered'), ('order_cancelled', 'Order Cancelled'), ('rider_assigned', 'Rider Assigned'), ('rider_near', 'Rider Near You'), ('payment_reminder', 'Payment Reminder'), ('general', 'General')], default='general', max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('email_sent', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='shop.order')),
            ],
            options={
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('unit', models.CharField(choices=[('kg', 'কিলোগ্রাম (kg)'), ('gram', 'গ্রাম (g)'), ('litre', 'লিটার (L)'), ('ml', 'মিলিলিটার (ml)'), ('piece', 'পিস'), ('packet', 'প্যাকেট'), ('box', 'বক্স'), ('bunch', 'বাঁড়ি/গুচ্ছ'), ('dozen', 'ডজন')], default='piece', help_text='পণ্যের ইউনিট', max_length=20)),
                ('image', models.ImageField(upload_to='products/')),
                ('stock', models.PositiveIntegerField(default=50)),
                ('is_available', models.BooleanField(default=True)),
                ('delivery_time', models.PositiveIntegerField(default=45, help_text='ডেলিভারি সময় (মিনিটে)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.category')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.zone')),
            ],
            options={
                'verbose_name_plural': 'Products',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
            ],
            options={
                'verbose_name_plural': 'Order Items',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('customer', 'গ্রাহক'), ('admin', 'অ্যাডমিন'), ('rider', 'রাইডার'), ('manager', 'ম্যানেজার')], default='customer', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('joined_date', models.DateTimeField(auto_now_add=True)),
                ('is_active_rider', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
                ('zone_assigned', models.ForeignKey(blank=True, help_text='যে Zone এর জন্য এই Manager দায়ী', null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.zone')),
            ],
            options={
                'verbose_name_plural': 'User Profiles',
            },
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_location_lat', models.FloatField(blank=True, null=True)),
                ('last_location_lng', models.FloatField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('favorite_products', models.ManyToManyField(blank=True, to='shop.product')),
                ('preferred_categories', models.ManyToManyField(blank=True, to='shop.category')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('preferred_zones', models.ManyToManyField(blank=True, to='shop.zone')),
            ],
            options={
                'verbose_name_plural': 'User Preferences',
            },
        ),
        migrations.CreateModel(
            name='ProductRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0.0, help_text='Recommendation score (0-1)')),
                ('reason', models.CharField(choices=[('location_based', 'Location Based'), ('category_based', 'Category Based'), ('purchase_history', 'Purchase History'), ('popular', 'Popular Products'), ('trending', 'Trending Now'), ('similar_users', 'Similar Users'), ('time_based', 'Time Based')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Product Recommendations',
                'ordering': ['-score', '-created_at'],
                'unique_together': {('user', 'product')},
            },
        ),
        migrations.CreateModel(
            name='ProductView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('session_id', models.CharField(blank=True, help_text='For anonymous users', max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Product Views',
                'ordering': ['-viewed_at'],
                'unique_together': {('user', 'product', 'session_id')},
            },
        ),
    ]
