# Generated by Django 5.1.7 on 2026-04-05 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_zone_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='latitude',
            field=models.FloatField(blank=True, help_text='Center latitude of service zone', null=True),
        ),
        migrations.AddField(
            model_name='zone',
            name='longitude',
            field=models.FloatField(blank=True, help_text='Center longitude of service zone', null=True),
        ),
        migrations.AddField(
            model_name='zone',
            name='radius',
            field=models.IntegerField(default=2000, help_text='Service radius in meters (e.g. 2000 = 2km)'),
        ),
    ]
