# Generated by Django 5.1.7 on 2026-04-06 11:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_order_customer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address_formatted',
            field=models.TextField(blank=True, help_text='Google Maps থেকে formatted address', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='manager',
            field=models.ForeignKey(blank=True, help_text='যে Manager এই অর্ডার approve করেছে', limit_choices_to={'profile__role': 'manager'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='manager_approval_reason',
            field=models.TextField(blank=True, help_text='Rejection reason if declined', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='manager_responded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='zone_assigned',
            field=models.ForeignKey(blank=True, help_text='যে Zone এর জন্য এই Manager দায়ী', null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.zone'),
        ),
        migrations.AlterField(
            model_name='order',
            name='rider',
            field=models.ForeignKey(blank=True, help_text='যে Rider deliver করবে', limit_choices_to={'profile__role': 'rider'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'অপেক্ষায়'), ('approved', 'অনুমোদিত'), ('confirmed', 'নিশ্চিত'), ('picked', 'রাইডার নিয়েছে'), ('delivered', 'ডেলিভার হয়েছে'), ('cancelled', 'বাতিল')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('customer', 'গ্রাহক'), ('rider', 'রাইডার'), ('manager', 'ম্যানেজার')], default='customer', max_length=20),
        ),
    ]
