# Generated by Django 5.1.7 on 2026-04-12 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('button_text', models.CharField(default='Order Now', max_length=100)),
                ('button_link', models.CharField(default='/register/', help_text='URL to navigate when button is clicked', max_length=300)),
                ('background_image', models.ImageField(upload_to='hero_slides/')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order of slides')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Hero Slides',
                'ordering': ['order'],
            },
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('customer', 'গ্রাহক'), ('admin', 'অ্যাডমিন'), ('rider', 'রাইডার'), ('manager', 'ম্যানেজার')], default='customer', max_length=20),
        ),
    ]
