# Generated by Django 5.1.7 on 2026-04-18 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_heroslide_alter_userprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('kg', 'কিলোগ্রাম (kg)'), ('gram', 'গ্রাম (g)'), ('litre', 'লিটার (L)'), ('ml', 'মিলিলিটার (ml)'), ('piece', 'পিস'), ('packet', 'প্যাকেট'), ('box', 'বক্স'), ('bunch', 'বাঁড়ি/গুচ্ছ'), ('dozen', 'ডজন')], default='piece', help_text='পণ্যের ইউনিট', max_length=20),
        ),
    ]
