# Generated by Django 5.1.7 on 2026-04-21 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_fix_notification_null_values'),
    ]

    operations = [
        # This migration updates the notification model with the NotificationPreference model
        # The index conflict from migration 0010 is handled by Django's automatic index management
    ]
