# Generated by Django 5.1.7 on 2026-04-21 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_fix_notification_null_values'),
    ]

    operations = [
        # Remove the problematic indexes from migration 0010
        migrations.RemoveIndex(
            model_name='notification',
            name='shop_notifi_user_id_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='shop_notifi_user_id_is_read_idx',
        ),
        # Add the correct index matching the current model
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', '-created_at'], name='shop_notifi_user_m_created_idx'),
        ),
    ]
